# Generated by Django 5.0 on 2024-01-10 19:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenID', models.CharField(max_length=20)),
                ('tokenClass', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'RFID Tokens',
            },
        ),
        migrations.CreateModel(
            name='Wallbox',
            fields=[
                ('serial', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product', models.CharField(default='unknown', max_length=255)),
                ('firmwareVersion', models.CharField(default='unknown', max_length=255)),
                ('timeStatus', models.CharField(choices=[('UC_TQ_NONE', 'No time quality. Clock was never set.'), ('UC_TQ_NOT_SYNCED', 'Clock was set but not really synchronized e.g. build time was used.'), ('UC_TQ_WEAK', 'Clock was synchronized using an unreliable source.'), ('UC_TQ_STRONG', 'Clock was synchronized using a reliable source (NTP, OCPP, etc.).'), ('UC_TQ_UNKNOWN', 'Time quality is unknown.')], default='UC_TQ_UNKNOWN', max_length=255)),
                ('state', models.CharField(choices=[('STATE_STARTUP', 'Startup'), ('STATE_NOT_READY', 'Not ready for charging, authorization locked or not connected to vehicle'), ('STATE_READY', 'Ready for charging and waiting for reaction from vehicle'), ('STATE_CHARGING', 'Charging'), ('STATE_ERROR', 'Error is present'), ('STATE_INTERRUPTED', 'Temporarily interrupted'), ('STATE_UNKNOWN', 'Unknown')], default='STATE_UNKNOWN', max_length=255)),
                ('plug', models.CharField(choices=[('PLUG_CABLE_UNPLUGGED', 'No cable is plugged.'), ('PLUG_CABLE_UNLOCKED_NOT_CONNECTED', 'Cable is plugged into charging station, but not connected or locked.'), ('PLUG_CABLE_LOCKED_NOT_CONNECTED', 'Cable is plugged into charging station and locked, but not connected to vehicle.'), ('PLUG_CABLE_CONNECTED_UNLOCKED', 'Cable is plugged into charging station and vehicle but not locked.'), ('PLUG_CABLE_CONNECTED_LOCKED', 'Cable is plugged into charging station and vehicle, furthermore the cable is locked.'), ('PLUG_CABLE_UNKNOWN', 'Cable status is unknown.')], default='PLUG_CABLE_UNKNOWN', max_length=255)),
                ('currentChargePower', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=9)),
                ('currentPowerFactor', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4)),
                ('currentSession', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=9)),
                ('energyMeter', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Wallboxes',
            },
        ),
        migrations.CreateModel(
            name='ChargeSession',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sessionID', models.IntegerField(primary_key=True, serialize=False)),
                ('hardwareCurrentLimit', models.IntegerField()),
                ('energyMeterAtStart', models.DecimalField(decimal_places=1, max_digits=9)),
                ('chargedEnergy', models.DecimalField(decimal_places=1, max_digits=9)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('timesource', models.CharField(choices=[('WALLBOX_TIME_NTP', 'Wallbox self-synchronized NTP time'), ('WALLBOX_TIME_WEAK', 'Wallbox weak synced time'), ('SERVER_TIME', 'Server time based on Wallbox timer offset'), ('TIME_UNKNOWN', 'Unknown time source')], default='TIME_UNKNOWN', max_length=255)),
                ('stopReason', models.CharField(choices=[('SESSION_RUNNING', 'Charging session has not ended.'), ('SESSION_CABLE_UNPLUGGED', 'Charging session was terminated by unplugging.'), ('SESSION_CARD_DEAUTH', 'Charging session was terminated via deauthorization with the RFID card used for starting the session.'), ('SESSION_STATUS_UNKNOWN', "The session's status is unknown.")], default='SESSION_STATUS_UNKNOWN', max_length=255)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rfidtoken')),
                ('wallboxSerial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.wallbox')),
            ],
            options={
                'ordering': ('sessionID',),
            },
        ),
    ]
