# Generated by Django 5.0 on 2024-01-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='wallbox',
            table_comment='Test Comment',
        ),
    ]
