# Generated by Django 5.0 on 2024-01-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wallbox_table_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallbox',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
