# Generated by Django 5.0 on 2024-01-19 18:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wallbox_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallbox',
            name='phase1_current',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='phase1_voltage',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='phase2_current',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='phase2_voltage',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='phase3_current',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='phase3_voltage',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3),
        ),
    ]
