# Generated by Django 5.0 on 2024-01-31 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wallbox_phase1_current_wallbox_phase1_voltage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallbox',
            name='uptime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
