# Generated by Django 5.0 on 2024-02-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rfidtoken_api_rfidtoken_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfidtoken',
            options={'verbose_name': 'RFID Token', 'verbose_name_plural': 'RFID Tokens'},
        ),
    ]
