# Generated by Django 5.0.3 on 2024-04-06 15:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rfidtoken_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallbox',
            name='currentEnergyMeterAtStart',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='currentHardwareLimit',
            field=models.IntegerField(default=Decimal('0')),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='currentSessionID',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='currentSessionStatus',
            field=models.CharField(choices=[('SESSION_RUNNING', 'Charging session has not ended.'), ('SESSION_CABLE_UNPLUGGED', 'Charging session was terminated by unplugging.'), ('SESSION_CARD_DEAUTH', 'Charging session was terminated via deauthorization with the RFID card used for starting the session.'), ('SESSION_STATUS_UNKNOWN', "The session's status is unknown.")], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='currentStartTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='wallbox',
            name='currentToken',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.rfidtoken'),
        ),
    ]
