version: "3"
volumes:
    db-data:

services:
  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - db.env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
        - "127.0.0.1:5432:5432"
  backend:
    build:
        context: ./backend
    env_file:
        - config.env
    #ports:
    #    - "127.0.0.1:8000:8000"
    #    - "0.0.0.0:7090:7090/udp"
    network_mode: host
    depends_on:
        - db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  frontend:
    build:
       context: ./frontend
    restart: unless-stopped
    ports:
       - "127.0.0.1:8001:80"
    security_opt:
      - no-new-privileges:true
